language: android
dist: trusty
android:
  components:
    - build-tools-28.0.3

    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
before_install:
  - chmod +x gradlew
  - openssl aes-256-cbc -K $encrypted_444d65c60933_key -iv $encrypted_444d65c60933_iv -in signing.tar.enc -out signing.tar -d
  - tar xvf signing.tar
script:
  - "./gradlew clean build"